language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - secure: TPZQOJ/KNkmdfnD4YyAWPs0AlRNJpjVZApyRqa3iagtOv4VwVeWrfFcW4YB3VLCiXfjU4W5Yewb3pfYA6IwsIPY0Y87M5SRrOgOYrsmEF4KErhr8zoTb6nTEMAyT8rpwhzKo2k98J5/f2iksrw7fexLjspTkcFZZCXC8Qc4azrx9v/kP3eUAnQVh2erjxnzLoGi6ZZwOA01L5ohInk1fp0nmf7Itrcp3wjtOAdnHpWD8BT+I2a6yvCyJ041ThToW6hioJXsDo4qXZk5SrUo1t2zsGz9mfNQKfcpyBLlaRnQtW1TWx0F77AKz+YKBX7gtZPyS9vBzOtmpoYiOZU9qKlZqsYmS91Rd5/ZqRVPTzGm6uRim6ZoeSPwYl5o2TQ8svO2C/LGE6BiipTbaJYyGhh3QJ3hOkvoMfm6sP9RS4OZmfbXQk911sjxR1tRgnI6+Tpsfsv7FgjEgAJW5MTRvoqbZokG9jibAwhZJhxBmmV74L0F++OcST9m0V1UjEM1ou1RSLg4Oy0Yx8aZQYZ7eDyIuHheVkaYzE5eHmdwWVI74TIDbESMHLzMFNsSDR6WxqElyWattJljVLDvmtPK3ARM/b4f3+pod6cxWNnR6dtdFJvG0h2VjYSZg36vFgb4/TVexuImmLiNpw+824++e0eJVgxq8SrITIWWmnhjRGwI=
sudo: required
before_script:
- alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"
- echo $MY_SECRET_ENV | tr '[A-Za-z]' '[N-ZA-Mn-za-m]'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia build_tarballs.jl
before_cache:
- rm -rf $(julia -e 'println(Pkg.dir("BinaryBuilder","deps","root"))')
deploy:
  provider: releases
  api_key:
    secure: p3D7Qm0CtV2vJYQIKfFVJiAgJigTKB2y6nEznumBRiAzVF2UkJJbKErmVtMKXIoYHBg4te+Md0rNtohEeI+zTrex0s51u/CbfKMiDg52aqwxX6XUYpeNlL5TTd4qENM+5hzo3Evs+9Qidy8iABftuLMfnOBFQIkh9BOlI5I8trl7UrlE0CzvL67uSTSqNDUFd2pNHwyqjhYzOU0s445MvFQnZPh2C29AmHIJkWnI332BmH+Ym0YatAeRyl/Oi09eZX9CGdBVuU75zagqVaH9YnIE4hCO1KO5WZxXOVTlS9X82EeVgWS+l2ecSFOiJpBZQCjZth6QvjvcG6m930Lr2rUa2WFlE47Qr46vhtjMUcroOkouA36lSHdLy1OskaubYQsYC5ixE2cF0+XW9/xqyzQbThV3FneVtb+Zm4bCFRkjsMVObtubYgIYyjbWz9H2Nj4HKlCtK9Ys3ZCOnbXcSxiEGP0k/LJbQ2oKzUhpMQZRKYHon3s/rrsvHwZXbwf9d2ksQhMdThPvEr47ELDVfktOOa1Eww7KFbnh3PYLAlVzz3/EnETTktl37S8nMSKFFR4hr2vQeKm3g7ik2hBylXHzETIjnlFOWUnO2Kpcc5nmQpnH7I4hQhNsg+oOrqyIRFCDFwFh2Dcxr5lyUAbF6nl7k62bGqo/8zSpZanzBXo=
  file_glob: true
  file: products/*.tar.gz
  skip_cleanup: true
  on:
    repo: Keno/IConvBuilder
    tags: true
