language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - secure: IMgSMkv41jfrOWlPnXIX7wqX9nlGKezPf/jKgYXih3G2DxQcgtKWWHPK9MCgYXfbNDMgnahk71o0mWl/C5CpXOK0H4HWcV1Xl1PU61zqhuLWpU/wcl7VC7hi530y0/Kya1Ps/fn5HbiDW6vrzRfkA7qCPWbu5aqdCoTr4fL011jrqMnprSFYLcr2ECGtY0f5JJbdiHZe4Pn6g+QoJraIuumvt7fUywYixWlBxkol3rJ9T8X206JMMnbg9n4UAPE3PIpzkD39p3ngbr0HxraDcqznBeLwAH9IpPRQy0boY6N0EBZJHnZg6RosnHJkZsIOPjpITnXF8GcthmLAQaX5SCi8TuualqDgxY0uIlUDJh5uqLKkMBo5NlttWq8BW4m8iMD8ESP94VsWA1XfGneF/A29DyX76G7WJiJ0CbZSTQDMMuPP20KVY2JXNJY9A+4aVxVH441E30TrOXh0jCExKwHsyYdaGSngU8GqfNM9BBzeVN0DHVlNVleiKVUXCd8cO4vFv/TISDI7xjFU8XVcvOqRXIDzT4wWO3Db2NXQhjhtGaZowP6p9bPJ/kOx5a/CQZA+wBoBwjBgrhUpvRSM+w75CbDiivO9UzOC3dO8Jg00W7HuszS3zdeyKmfcwvFBWK1BUPmpJaFA1TGjD6PxCWgKtEx13LNkxnip5tiH6JU=
sudo: required
before_script:
- alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"
- echo $MY_SECRET_ENV | tr '[A-Za-z]' '[N-ZA-Mn-za-m]'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia build_tarballs.jl
before_cache:
- rm -rf $(julia -e 'println(Pkg.dir("BinaryBuilder","deps","root"))')
deploy:
  provider: releases
  api_key:
    secure: p3D7Qm0CtV2vJYQIKfFVJiAgJigTKB2y6nEznumBRiAzVF2UkJJbKErmVtMKXIoYHBg4te+Md0rNtohEeI+zTrex0s51u/CbfKMiDg52aqwxX6XUYpeNlL5TTd4qENM+5hzo3Evs+9Qidy8iABftuLMfnOBFQIkh9BOlI5I8trl7UrlE0CzvL67uSTSqNDUFd2pNHwyqjhYzOU0s445MvFQnZPh2C29AmHIJkWnI332BmH+Ym0YatAeRyl/Oi09eZX9CGdBVuU75zagqVaH9YnIE4hCO1KO5WZxXOVTlS9X82EeVgWS+l2ecSFOiJpBZQCjZth6QvjvcG6m930Lr2rUa2WFlE47Qr46vhtjMUcroOkouA36lSHdLy1OskaubYQsYC5ixE2cF0+XW9/xqyzQbThV3FneVtb+Zm4bCFRkjsMVObtubYgIYyjbWz9H2Nj4HKlCtK9Ys3ZCOnbXcSxiEGP0k/LJbQ2oKzUhpMQZRKYHon3s/rrsvHwZXbwf9d2ksQhMdThPvEr47ELDVfktOOa1Eww7KFbnh3PYLAlVzz3/EnETTktl37S8nMSKFFR4hr2vQeKm3g7ik2hBylXHzETIjnlFOWUnO2Kpcc5nmQpnH7I4hQhNsg+oOrqyIRFCDFwFh2Dcxr5lyUAbF6nl7k62bGqo/8zSpZanzBXo=
  file_glob: true
  file: products/*.tar.gz
  skip_cleanup: true
  on:
    repo: Keno/IConvBuilder
    tags: true
