language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - secure: TPZQOJ/KNkmdfnD4YyAWPs0AlRNJpjVZApyRqa3iagtOv4VwVeWrfFcW4YB3VLCiXfjU4W5Yewb3pfYA6IwsIPY0Y87M5SRrOgOYrsmEF4KErhr8zoTb6nTEMAyT8rpwhzKo2k98J5/f2iksrw7fexLjspTkcFZZCXC8Qc4azrx9v/kP3eUAnQVh2erjxnzLoGi6ZZwOA01L5ohInk1fp0nmf7Itrcp3wjtOAdnHpWD8BT+I2a6yvCyJ041ThToW6hioJXsDo4qXZk5SrUo1t2zsGz9mfNQKfcpyBLlaRnQtW1TWx0F77AKz+YKBX7gtZPyS9vBzOtmpoYiOZU9qKlZqsYmS91Rd5/ZqRVPTzGm6uRim6ZoeSPwYl5o2TQ8svO2C/LGE6BiipTbaJYyGhh3QJ3hOkvoMfm6sP9RS4OZmfbXQk911sjxR1tRgnI6+Tpsfsv7FgjEgAJW5MTRvoqbZokG9jibAwhZJhxBmmV74L0F++OcST9m0V1UjEM1ou1RSLg4Oy0Yx8aZQYZ7eDyIuHheVkaYzE5eHmdwWVI74TIDbESMHLzMFNsSDR6WxqElyWattJljVLDvmtPK3ARM/b4f3+pod6cxWNnR6dtdFJvG0h2VjYSZg36vFgb4/TVexuImmLiNpw+824++e0eJVgxq8SrITIWWmnhjRGwI=
sudo: required
before_script:
- alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"
- echo $MY_SECRET_ENV | tr '[A-Za-z]' '[N-ZA-Mn-za-m]'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia build_tarballs.jl
before_cache:
- rm -rf $(julia -e 'println(Pkg.dir("BinaryBuilder","deps","root"))')
deploy:
  provider: releases
  api_key:
    secure: qgN9vl/DYCnER+I3cz//1V6f3cqSBdCTZnjmO7dCEr0SxVwyFZpL2Sb9118MNOyjW1aaqNm1RZ3oiv8OJlDAL14Y1P9XZSdGX/jJNx8Ej99iCV4qrkuZO+f2PObugNg1kWZ46a4Fp90D5GlR8cABP6wBASCgg8x9DULY0s25iDi0Q1Ho6qrI4XCSUEMJ7DHkv6HGEbHVBQq9nr9o0DFJ0Chqc76z9r3oa+WMXoDdYBOxvCrP3T8eAbQkeK3FptL2H78GcBqI1Q674oYJvTOk7x29K1T/x3MujbL5kv313ulk1xvbmUsuDR/Wgi4ReAVXfpwRFv4t+QkXwe06cO4uTciQyGAbnxKkuleYNtr8YoXwwCtan480Fpj3Jb834V/XMkIXMr23oUJ0t3UXRPpJiXdL0eiQJCmdjXHqYHfrFP+ajZeX8hMtGwuqDEDAvCw6eErmF8BsLscgi5Ow2kRIbh7HfNR7F1qbuc3qkzMpS7tdLMn2qbY8MjHK7XEFw5Vvz+KFsDTEWf29q5561n2Tb/pB2FY9pwfGY6/ItRBh3tjq5/V5Vd+SqVDiavZPsikoXG1Q4cvMmk2ATgES7hJL2mB7atjwzmUV/EiQluxH0jEEKd9zw7FzyyiIvGA/n0w1bGcIjG1m/lDicWQF7xT/ejdUgI1oYmvxkvlfe8xoY+c=
  file_glob: true
  file: products/*.tar.gz
  skip_cleanup: true
  on:
    repo: Keno/IConvBuilder
    tags: true
